### ISSUE TITLE
`ConfigEnvironmentReplacerReleaseWorker` not being used by monorepo builder

### ISSUE THREAD

**Issue by mallardduck** [mallardduck/kickflip-monorepo#1]
The gist is that the custom `ConfigEnvironmentReplacerReleaseWorker` step isn't getting recognized.
All the "default" workers are loaded just fine, but for some reason mine is not being used.

---

I did try a few different namespaces -wondering if I was doing something wrong- without any luck.
I even opted to try adding the class locally to the file but that didn't seem to help either.
However as I didn't capture any notes when I was debugging this I'm just going off my tired memory of last night.
So I'll need to re-debug these different attempts in this issue and track the results here.

**Comment by mallardduck** [comment]
Config with only 2 "stock" workers and my custom worker:

```
RESULT
± |main → public {1} ✓| → ./vendor/bin/monorepo-builder release minor --dry-run

1/2) Update "replace" version in "composer.json" to new tag to avoid circular dependencies conflicts
====================================================================================================

2/2) Set packages mutual dependencies to "^0.2" version
=======================================================

 ! [NOTE] Running in dry mode, nothing is changed
```

**Comment by mallardduck** [comment]
Config with inline class rule: https://github.com/mallardduck/kickflip-monorepo/commit/be7e3dae132fb2a1a98f044dd435a972519e29ef

```
 [ERROR] The definition for "ConfigEnvironmentReplacerReleaseWorker" has no class attribute, and appears to reference a
         class or interface in the global namespace. Leaving out the "class" attribute is only allowed for namespaced
         classes. Please specify the class attribute explicitly to get rid of this error.
```

**Comment by mallardduck** [comment]
Same inline worker class, but with both `set()` params: https://github.com/mallardduck/kickflip-monorepo/commit/7da8cf6aacb2cd6a0d5e581eb301b35f9eaa5411

```± |debug-monorepo-workers → origin {1} ✓| → ./vendor/bin/monorepo-builder release minor --dry-run

1/3) Update "replace" version in "composer.json" to new tag to avoid circular dependencies conflicts
====================================================================================================

2/3) Set packages mutual dependencies to "^0.2" version
=======================================================

3/3) Update config/app.php to production environment
====================================================

 ! [NOTE] Running in dry mode, nothing is changed
```

This is the closest to working!

**Comment by mallardduck** [comment]
Using the same change on `set()` but with the namespaced worker class: https://github.com/mallardduck/kickflip-monorepo/commit/1f58e2974f45f5745b1e08dbef5bb42fccc69480

```
± |debug-monorepo-workers → origin {1} U:1 ✗| → ./vendor/bin/monorepo-builder release minor --dry-run

1/2) Update "replace" version in "composer.json" to new tag to avoid circular dependencies conflicts
====================================================================================================

2/2) Set packages mutual dependencies to "^0.2" version
=======================================================

 ! [NOTE] Running in dry mode, nothing is changed
```

This is a step back now then for sure...weird AF.
So is it an error with how my worker is defined?: https://github.com/mallardduck/kickflip-monorepo/blob/debug-monorepo-workers/src/ConfigEnvironmentReplacerReleaseWorker.php 
Just failing silently?

**Comment by mallardduck** [comment]
With the same setup as the last comment, but upgraded to `symplify/monorepo-builder` 10: https://github.com/mallardduck/kickflip-monorepo/commit/0208ed45b93dee46d9ecceeeadd5d34d6bd4ab8f

```
± |debug-monorepo-workers → origin {1} U:2 ✗| → ./vendor/bin/monorepo-builder release minor --dry-run

1/3) Update "replace" version in "composer.json" to new tag to avoid circular dependencies conflicts
====================================================================================================

2/3) Set packages mutual dependencies to "^0.2" version
=======================================================

3/3) Update config/app.php to production environment
====================================================

 ! [NOTE] Running in dry mode, nothing is changed
```

**Comment by mallardduck** [comment]
Based on chat with @TomasVotruba [here](https://github.com/mallardduck/kickflip-monorepo/commit/50d5aba119cdfc20a8115e6e826fdb8182a707a2), this was just a bug I was running into that's fixed with monorepo-builder 10!

Thanks again for the help Tomas!

**Comment by TomasVotruba** [comment]
Thank you :+1:  and sorry for the troubles :bow:

**Comment by mallardduck** [comment]
No troubles at all, just chances to learn!
Really appreciate your help with all this as I "get my sea legs" with monorepo.
